### ISSUE TITLE
Unintialized Constant Error

### ISSUE THREAD

**Issue by nomanurrehman** [lbeder/health-monitor-rails#51] opened 2019-05-06 14:31 UTC
I have followed the exact instructions to add the gem from the `README` file but I am getting the following error.

```
uninitialized constant HealthMonitor (NameError)
```

I have added it to a Rails api-only application. My Ruby version is `2.6.2` and Rails version is `~> 5.2.3`

Is this supposed to work with only a full-Rails application, and not an api?

**Comment by lbeder** [comment] 2019-05-06 16:22
Strange, it should've worked. I'll check it out soon.

**Comment by lbeder** [comment] 2019-05-06 17:53
I'm unable to reproduce it. Could you please create a sample app, which you could share with me, that reproduces the issue?

**Comment by nomanurrehman** [comment] 2019-05-07 10:17
Here is a vanilla Rails application with the gem added that produces the said error.

https://github.com/nomanurrehman/health-monitor-test

I am also getting the same error in my other Rails application.

**Comment by lbeder** [comment] 2019-05-07 14:06
Ah, it looks like it's related to the newer eager loading. I'll work on a fix.

**Comment by lbeder** [comment] 2019-05-07 14:27
It's actually because you're missing a `require` to the module in your `routes.rb` (which is usually a side effect of having a custom initializer, which you don't have).

Please add `require 'health_monitor/engine'` to your `routes.rb` file and let me know if it works. In the meantime, I'll update the documentation accordingly.

**Comment by lbeder** [comment] 2019-05-09 07:15
@nomanurrehman were you able to check if this works?

**Comment by nomanurrehman** [comment] 2019-05-09 08:21
@lbeder Still not able to make this work.

Here is my `routes.rb` file.

```
require 'health_monitor/engine'

Rails.application.routes.draw do
  # Mounts the health check end-point
  mount HealthMonitor::Engine, at: '/'

  # { ... other application routes ... }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
```

Here is what `rails routes` command says.

[Command output](https://imgur.com/cqIhjCV)

No status page available at `http://localhost:3000`, `http://localhost:3000/check`, `http://localhost:3000/health`, `http://localhost:3000/health_check`.

**Comment by lbeder** [comment] 2019-05-09 18:36
This looks like a different issue. I'll push a fix soon.

**Comment by lbeder** [comment] 2019-05-09 19:25
Huh, apparently it was all related after all :). I've fixed the autoloading issue (which means that you no longer need the previous `require 'health_monitor/engine'`) and have verified it with your test app. 

The fix is available as version `8.6.0`. Could you verify that it works on your side as well?

**Comment by lbeder** [comment] 2019-05-11 10:33
@nomanurrehman any luck?

**Comment by nomanurrehman** [comment] 2019-05-11 18:29
Not yet. I have not had the time to move forward on this. Will update in a couple of days when I get the chance to. Thanks for looking into it.

**Comment by navidemad** [comment] 2019-05-17 09:34
@lbeder I confirmed that the first bug is now fixed 👍

But now I am receiving with : `gem "health-monitor-rails", github: "lbeder/health-monitor-rails"`

```ruby
config/initializers/health_monitor.rb:2:in `block in <main>': undefined method `configure' for HealthMonitor:Module`
```
```ruby
Rails.application.config.after_initialize do
  HealthMonitor.configure do |health_monitor_config|
    health_monitor_config.redis.configure do |health_monitor_redis_config|
      health_monitor_redis_config.connection = Redis.current
      health_monitor_redis_config.max_used_memory = 200
    end
```

**Comment by lbeder** [comment] 2019-05-17 12:55
Thanks for checking it. It seems an unfortunate regression due to my previous fix. I've pushed the fix.

**Comment by lbeder** [comment] 2019-05-28 17:42
@navidemad, could you please check if it works now?

**Closed** 2019-05-31 11:02 UTC
